/*
 * Copyright (C) 2013-  Qiming Sun <osirpt.sun@gmail.com>
 * Description: code generated by  gen-code.cl
 */
#include <stdlib.h>
#include <stdio.h>
#include "cint_bas.h"
#include "cart2sph.h"
#include "g1e.h"
#include "g1e_grids.h"
#include "g2e.h"
#include "optimizer.h"
#include "cint1e.h"
#include "cint2e.h"
#include "misc.h"
#include "c2f.h"
/* <NABLA i|OVLP |j> */
void CINTgout1e_int1e_ipovlp(double *gout, double *g, FINT *idx, CINTEnvVars *envs, FINT gout_empty) {
FINT nf = envs->nf;
FINT ix, iy, iz, n;
double *g0 = g;
double *g1 = g0 + envs->g_size * 3;
double s[3];
G1E_D_I(g1, g0, envs->i_l+0, envs->j_l, 0);
for (n = 0; n < nf; n++) {
ix = idx[0+n*3];
iy = idx[1+n*3];
iz = idx[2+n*3];
s[0] = + g1[ix+0]*g0[iy+0]*g0[iz+0];
s[1] = + g0[ix+0]*g1[iy+0]*g0[iz+0];
s[2] = + g0[ix+0]*g0[iy+0]*g1[iz+0];
if (gout_empty) {
gout[n*3+0] = + s[0];
gout[n*3+1] = + s[1];
gout[n*3+2] = + s[2];
} else {
gout[n*3+0] += + s[0];
gout[n*3+1] += + s[1];
gout[n*3+2] += + s[2];
}}}
void int1e_ipovlp_optimizer(CINTOpt **opt, FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env) {
FINT ng[] = {1, 0, 0, 0, 1, 1, 1, 3};
CINTall_1e_optimizer(opt, ng, atm, natm, bas, nbas, env);
}
CACHE_SIZE_T int1e_ipovlp_cart(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {1, 0, 0, 0, 1, 1, 1, 3};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipovlp;
return CINT1e_drv(out, dims, &envs, cache, &c2s_cart_1e, 0);
} // int1e_ipovlp_cart
CACHE_SIZE_T int1e_ipovlp_sph(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {1, 0, 0, 0, 1, 1, 1, 3};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipovlp;
return CINT1e_drv(out, dims, &envs, cache, &c2s_sph_1e, 0);
} // int1e_ipovlp_sph
CACHE_SIZE_T int1e_ipovlp_spinor(double complex *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {1, 0, 0, 0, 1, 1, 1, 3};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipovlp;
return CINT1e_spinor_drv(out, dims, &envs, cache, &c2s_sf_1e, 0);
} // int1e_ipovlp_spinor
ALL_CINT1E(int1e_ipovlp)
ALL_CINT1E_FORTRAN_(int1e_ipovlp)
/* <i|OVLP |NABLA j> */
void CINTgout1e_int1e_ovlpip(double *gout, double *g, FINT *idx, CINTEnvVars *envs, FINT gout_empty) {
FINT nf = envs->nf;
FINT ix, iy, iz, n;
double *g0 = g;
double *g1 = g0 + envs->g_size * 3;
double s[3];
G1E_D_J(g1, g0, envs->i_l+0, envs->j_l+0, 0);
for (n = 0; n < nf; n++) {
ix = idx[0+n*3];
iy = idx[1+n*3];
iz = idx[2+n*3];
s[0] = + g1[ix+0]*g0[iy+0]*g0[iz+0];
s[1] = + g0[ix+0]*g1[iy+0]*g0[iz+0];
s[2] = + g0[ix+0]*g0[iy+0]*g1[iz+0];
if (gout_empty) {
gout[n*3+0] = + s[0];
gout[n*3+1] = + s[1];
gout[n*3+2] = + s[2];
} else {
gout[n*3+0] += + s[0];
gout[n*3+1] += + s[1];
gout[n*3+2] += + s[2];
}}}
void int1e_ovlpip_optimizer(CINTOpt **opt, FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env) {
FINT ng[] = {0, 1, 0, 0, 1, 1, 1, 3};
CINTall_1e_optimizer(opt, ng, atm, natm, bas, nbas, env);
}
CACHE_SIZE_T int1e_ovlpip_cart(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {0, 1, 0, 0, 1, 1, 1, 3};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ovlpip;
return CINT1e_drv(out, dims, &envs, cache, &c2s_cart_1e, 0);
} // int1e_ovlpip_cart
CACHE_SIZE_T int1e_ovlpip_sph(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {0, 1, 0, 0, 1, 1, 1, 3};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ovlpip;
return CINT1e_drv(out, dims, &envs, cache, &c2s_sph_1e, 0);
} // int1e_ovlpip_sph
CACHE_SIZE_T int1e_ovlpip_spinor(double complex *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {0, 1, 0, 0, 1, 1, 1, 3};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ovlpip;
return CINT1e_spinor_drv(out, dims, &envs, cache, &c2s_sf_1e, 0);
} // int1e_ovlpip_spinor
ALL_CINT1E(int1e_ovlpip)
ALL_CINT1E_FORTRAN_(int1e_ovlpip)
/* <NABLA NABLA i|OVLP |j> */
void CINTgout1e_int1e_ipipovlp(double *gout, double *g, FINT *idx, CINTEnvVars *envs, FINT gout_empty) {
FINT nf = envs->nf;
FINT ix, iy, iz, n;
double *g0 = g;
double *g1 = g0 + envs->g_size * 3;
double *g2 = g1 + envs->g_size * 3;
double *g3 = g2 + envs->g_size * 3;
double s[9];
G1E_D_I(g1, g0, envs->i_l+1, envs->j_l, 0);
G1E_D_I(g2, g0, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g3, g1, envs->i_l+0, envs->j_l, 0);
for (n = 0; n < nf; n++) {
ix = idx[0+n*3];
iy = idx[1+n*3];
iz = idx[2+n*3];
s[0] = + g3[ix+0]*g0[iy+0]*g0[iz+0];
s[1] = + g2[ix+0]*g1[iy+0]*g0[iz+0];
s[2] = + g2[ix+0]*g0[iy+0]*g1[iz+0];
s[3] = + g1[ix+0]*g2[iy+0]*g0[iz+0];
s[4] = + g0[ix+0]*g3[iy+0]*g0[iz+0];
s[5] = + g0[ix+0]*g2[iy+0]*g1[iz+0];
s[6] = + g1[ix+0]*g0[iy+0]*g2[iz+0];
s[7] = + g0[ix+0]*g1[iy+0]*g2[iz+0];
s[8] = + g0[ix+0]*g0[iy+0]*g3[iz+0];
if (gout_empty) {
gout[n*9+0] = + s[0];
gout[n*9+1] = + s[3];
gout[n*9+2] = + s[6];
gout[n*9+3] = + s[1];
gout[n*9+4] = + s[4];
gout[n*9+5] = + s[7];
gout[n*9+6] = + s[2];
gout[n*9+7] = + s[5];
gout[n*9+8] = + s[8];
} else {
gout[n*9+0] += + s[0];
gout[n*9+1] += + s[3];
gout[n*9+2] += + s[6];
gout[n*9+3] += + s[1];
gout[n*9+4] += + s[4];
gout[n*9+5] += + s[7];
gout[n*9+6] += + s[2];
gout[n*9+7] += + s[5];
gout[n*9+8] += + s[8];
}}}
void int1e_ipipovlp_optimizer(CINTOpt **opt, FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env) {
FINT ng[] = {2, 0, 0, 0, 2, 1, 1, 9};
CINTall_1e_optimizer(opt, ng, atm, natm, bas, nbas, env);
}
CACHE_SIZE_T int1e_ipipovlp_cart(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {2, 0, 0, 0, 2, 1, 1, 9};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipovlp;
return CINT1e_drv(out, dims, &envs, cache, &c2s_cart_1e, 0);
} // int1e_ipipovlp_cart
CACHE_SIZE_T int1e_ipipovlp_sph(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {2, 0, 0, 0, 2, 1, 1, 9};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipovlp;
return CINT1e_drv(out, dims, &envs, cache, &c2s_sph_1e, 0);
} // int1e_ipipovlp_sph
CACHE_SIZE_T int1e_ipipovlp_spinor(double complex *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {2, 0, 0, 0, 2, 1, 1, 9};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipovlp;
return CINT1e_spinor_drv(out, dims, &envs, cache, &c2s_sf_1e, 0);
} // int1e_ipipovlp_spinor
ALL_CINT1E(int1e_ipipovlp)
ALL_CINT1E_FORTRAN_(int1e_ipipovlp)
/* <NABLA i|OVLP |NABLA j> */
void CINTgout1e_int1e_ipovlpip(double *gout, double *g, FINT *idx, CINTEnvVars *envs, FINT gout_empty) {
FINT nf = envs->nf;
FINT ix, iy, iz, n;
double *g0 = g;
double *g1 = g0 + envs->g_size * 3;
double *g2 = g1 + envs->g_size * 3;
double *g3 = g2 + envs->g_size * 3;
double s[9];
G1E_D_J(g1, g0, envs->i_l+1, envs->j_l+0, 0);
G1E_D_I(g2, g0, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g3, g1, envs->i_l+0, envs->j_l, 0);
for (n = 0; n < nf; n++) {
ix = idx[0+n*3];
iy = idx[1+n*3];
iz = idx[2+n*3];
s[0] = + g3[ix+0]*g0[iy+0]*g0[iz+0];
s[1] = + g2[ix+0]*g1[iy+0]*g0[iz+0];
s[2] = + g2[ix+0]*g0[iy+0]*g1[iz+0];
s[3] = + g1[ix+0]*g2[iy+0]*g0[iz+0];
s[4] = + g0[ix+0]*g3[iy+0]*g0[iz+0];
s[5] = + g0[ix+0]*g2[iy+0]*g1[iz+0];
s[6] = + g1[ix+0]*g0[iy+0]*g2[iz+0];
s[7] = + g0[ix+0]*g1[iy+0]*g2[iz+0];
s[8] = + g0[ix+0]*g0[iy+0]*g3[iz+0];
if (gout_empty) {
gout[n*9+0] = + s[0];
gout[n*9+1] = + s[1];
gout[n*9+2] = + s[2];
gout[n*9+3] = + s[3];
gout[n*9+4] = + s[4];
gout[n*9+5] = + s[5];
gout[n*9+6] = + s[6];
gout[n*9+7] = + s[7];
gout[n*9+8] = + s[8];
} else {
gout[n*9+0] += + s[0];
gout[n*9+1] += + s[1];
gout[n*9+2] += + s[2];
gout[n*9+3] += + s[3];
gout[n*9+4] += + s[4];
gout[n*9+5] += + s[5];
gout[n*9+6] += + s[6];
gout[n*9+7] += + s[7];
gout[n*9+8] += + s[8];
}}}
void int1e_ipovlpip_optimizer(CINTOpt **opt, FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env) {
FINT ng[] = {1, 1, 0, 0, 2, 1, 1, 9};
CINTall_1e_optimizer(opt, ng, atm, natm, bas, nbas, env);
}
CACHE_SIZE_T int1e_ipovlpip_cart(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {1, 1, 0, 0, 2, 1, 1, 9};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipovlpip;
return CINT1e_drv(out, dims, &envs, cache, &c2s_cart_1e, 0);
} // int1e_ipovlpip_cart
CACHE_SIZE_T int1e_ipovlpip_sph(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {1, 1, 0, 0, 2, 1, 1, 9};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipovlpip;
return CINT1e_drv(out, dims, &envs, cache, &c2s_sph_1e, 0);
} // int1e_ipovlpip_sph
CACHE_SIZE_T int1e_ipovlpip_spinor(double complex *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {1, 1, 0, 0, 2, 1, 1, 9};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipovlpip;
return CINT1e_spinor_drv(out, dims, &envs, cache, &c2s_sf_1e, 0);
} // int1e_ipovlpip_spinor
ALL_CINT1E(int1e_ipovlpip)
ALL_CINT1E_FORTRAN_(int1e_ipovlpip)
/* <NABLA NABLA NABLA i|OVLP |j> */
void CINTgout1e_int1e_ipipipovlp(double *gout, double *g, FINT *idx, CINTEnvVars *envs, FINT gout_empty) {
FINT nf = envs->nf;
FINT ix, iy, iz, n;
double *g0 = g;
double *g1 = g0 + envs->g_size * 3;
double *g2 = g1 + envs->g_size * 3;
double *g3 = g2 + envs->g_size * 3;
double *g4 = g3 + envs->g_size * 3;
double *g5 = g4 + envs->g_size * 3;
double *g6 = g5 + envs->g_size * 3;
double *g7 = g6 + envs->g_size * 3;
double s[27];
G1E_D_I(g1, g0, envs->i_l+2, envs->j_l, 0);
G1E_D_I(g2, g0, envs->i_l+1, envs->j_l, 0);
G1E_D_I(g3, g1, envs->i_l+1, envs->j_l, 0);
G1E_D_I(g4, g0, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g5, g1, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g6, g2, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g7, g3, envs->i_l+0, envs->j_l, 0);
for (n = 0; n < nf; n++) {
ix = idx[0+n*3];
iy = idx[1+n*3];
iz = idx[2+n*3];
s[0] = + g7[ix+0]*g0[iy+0]*g0[iz+0];
s[1] = + g6[ix+0]*g1[iy+0]*g0[iz+0];
s[2] = + g6[ix+0]*g0[iy+0]*g1[iz+0];
s[3] = + g5[ix+0]*g2[iy+0]*g0[iz+0];
s[4] = + g4[ix+0]*g3[iy+0]*g0[iz+0];
s[5] = + g4[ix+0]*g2[iy+0]*g1[iz+0];
s[6] = + g5[ix+0]*g0[iy+0]*g2[iz+0];
s[7] = + g4[ix+0]*g1[iy+0]*g2[iz+0];
s[8] = + g4[ix+0]*g0[iy+0]*g3[iz+0];
s[9] = + g3[ix+0]*g4[iy+0]*g0[iz+0];
s[10] = + g2[ix+0]*g5[iy+0]*g0[iz+0];
s[11] = + g2[ix+0]*g4[iy+0]*g1[iz+0];
s[12] = + g1[ix+0]*g6[iy+0]*g0[iz+0];
s[13] = + g0[ix+0]*g7[iy+0]*g0[iz+0];
s[14] = + g0[ix+0]*g6[iy+0]*g1[iz+0];
s[15] = + g1[ix+0]*g4[iy+0]*g2[iz+0];
s[16] = + g0[ix+0]*g5[iy+0]*g2[iz+0];
s[17] = + g0[ix+0]*g4[iy+0]*g3[iz+0];
s[18] = + g3[ix+0]*g0[iy+0]*g4[iz+0];
s[19] = + g2[ix+0]*g1[iy+0]*g4[iz+0];
s[20] = + g2[ix+0]*g0[iy+0]*g5[iz+0];
s[21] = + g1[ix+0]*g2[iy+0]*g4[iz+0];
s[22] = + g0[ix+0]*g3[iy+0]*g4[iz+0];
s[23] = + g0[ix+0]*g2[iy+0]*g5[iz+0];
s[24] = + g1[ix+0]*g0[iy+0]*g6[iz+0];
s[25] = + g0[ix+0]*g1[iy+0]*g6[iz+0];
s[26] = + g0[ix+0]*g0[iy+0]*g7[iz+0];
if (gout_empty) {
gout[n*27+0] = + s[0];
gout[n*27+1] = + s[9];
gout[n*27+2] = + s[18];
gout[n*27+3] = + s[3];
gout[n*27+4] = + s[12];
gout[n*27+5] = + s[21];
gout[n*27+6] = + s[6];
gout[n*27+7] = + s[15];
gout[n*27+8] = + s[24];
gout[n*27+9] = + s[1];
gout[n*27+10] = + s[10];
gout[n*27+11] = + s[19];
gout[n*27+12] = + s[4];
gout[n*27+13] = + s[13];
gout[n*27+14] = + s[22];
gout[n*27+15] = + s[7];
gout[n*27+16] = + s[16];
gout[n*27+17] = + s[25];
gout[n*27+18] = + s[2];
gout[n*27+19] = + s[11];
gout[n*27+20] = + s[20];
gout[n*27+21] = + s[5];
gout[n*27+22] = + s[14];
gout[n*27+23] = + s[23];
gout[n*27+24] = + s[8];
gout[n*27+25] = + s[17];
gout[n*27+26] = + s[26];
} else {
gout[n*27+0] += + s[0];
gout[n*27+1] += + s[9];
gout[n*27+2] += + s[18];
gout[n*27+3] += + s[3];
gout[n*27+4] += + s[12];
gout[n*27+5] += + s[21];
gout[n*27+6] += + s[6];
gout[n*27+7] += + s[15];
gout[n*27+8] += + s[24];
gout[n*27+9] += + s[1];
gout[n*27+10] += + s[10];
gout[n*27+11] += + s[19];
gout[n*27+12] += + s[4];
gout[n*27+13] += + s[13];
gout[n*27+14] += + s[22];
gout[n*27+15] += + s[7];
gout[n*27+16] += + s[16];
gout[n*27+17] += + s[25];
gout[n*27+18] += + s[2];
gout[n*27+19] += + s[11];
gout[n*27+20] += + s[20];
gout[n*27+21] += + s[5];
gout[n*27+22] += + s[14];
gout[n*27+23] += + s[23];
gout[n*27+24] += + s[8];
gout[n*27+25] += + s[17];
gout[n*27+26] += + s[26];
}}}
void int1e_ipipipovlp_optimizer(CINTOpt **opt, FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env) {
FINT ng[] = {3, 0, 0, 0, 3, 1, 1, 27};
CINTall_1e_optimizer(opt, ng, atm, natm, bas, nbas, env);
}
CACHE_SIZE_T int1e_ipipipovlp_cart(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {3, 0, 0, 0, 3, 1, 1, 27};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipipovlp;
return CINT1e_drv(out, dims, &envs, cache, &c2s_cart_1e, 0);
} // int1e_ipipipovlp_cart
CACHE_SIZE_T int1e_ipipipovlp_sph(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {3, 0, 0, 0, 3, 1, 1, 27};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipipovlp;
return CINT1e_drv(out, dims, &envs, cache, &c2s_sph_1e, 0);
} // int1e_ipipipovlp_sph
CACHE_SIZE_T int1e_ipipipovlp_spinor(double complex *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {3, 0, 0, 0, 3, 1, 1, 27};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipipovlp;
return CINT1e_spinor_drv(out, dims, &envs, cache, &c2s_sf_1e, 0);
} // int1e_ipipipovlp_spinor
ALL_CINT1E(int1e_ipipipovlp)
ALL_CINT1E_FORTRAN_(int1e_ipipipovlp)
/* <NABLA NABLA i|OVLP |NABLA j> */
void CINTgout1e_int1e_ipipovlpip(double *gout, double *g, FINT *idx, CINTEnvVars *envs, FINT gout_empty) {
FINT nf = envs->nf;
FINT ix, iy, iz, n;
double *g0 = g;
double *g1 = g0 + envs->g_size * 3;
double *g2 = g1 + envs->g_size * 3;
double *g3 = g2 + envs->g_size * 3;
double *g4 = g3 + envs->g_size * 3;
double *g5 = g4 + envs->g_size * 3;
double *g6 = g5 + envs->g_size * 3;
double *g7 = g6 + envs->g_size * 3;
double s[27];
G1E_D_J(g1, g0, envs->i_l+2, envs->j_l+0, 0);
G1E_D_I(g2, g0, envs->i_l+1, envs->j_l, 0);
G1E_D_I(g3, g1, envs->i_l+1, envs->j_l, 0);
G1E_D_I(g4, g0, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g5, g1, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g6, g2, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g7, g3, envs->i_l+0, envs->j_l, 0);
for (n = 0; n < nf; n++) {
ix = idx[0+n*3];
iy = idx[1+n*3];
iz = idx[2+n*3];
s[0] = + g7[ix+0]*g0[iy+0]*g0[iz+0];
s[1] = + g6[ix+0]*g1[iy+0]*g0[iz+0];
s[2] = + g6[ix+0]*g0[iy+0]*g1[iz+0];
s[3] = + g5[ix+0]*g2[iy+0]*g0[iz+0];
s[4] = + g4[ix+0]*g3[iy+0]*g0[iz+0];
s[5] = + g4[ix+0]*g2[iy+0]*g1[iz+0];
s[6] = + g5[ix+0]*g0[iy+0]*g2[iz+0];
s[7] = + g4[ix+0]*g1[iy+0]*g2[iz+0];
s[8] = + g4[ix+0]*g0[iy+0]*g3[iz+0];
s[9] = + g3[ix+0]*g4[iy+0]*g0[iz+0];
s[10] = + g2[ix+0]*g5[iy+0]*g0[iz+0];
s[11] = + g2[ix+0]*g4[iy+0]*g1[iz+0];
s[12] = + g1[ix+0]*g6[iy+0]*g0[iz+0];
s[13] = + g0[ix+0]*g7[iy+0]*g0[iz+0];
s[14] = + g0[ix+0]*g6[iy+0]*g1[iz+0];
s[15] = + g1[ix+0]*g4[iy+0]*g2[iz+0];
s[16] = + g0[ix+0]*g5[iy+0]*g2[iz+0];
s[17] = + g0[ix+0]*g4[iy+0]*g3[iz+0];
s[18] = + g3[ix+0]*g0[iy+0]*g4[iz+0];
s[19] = + g2[ix+0]*g1[iy+0]*g4[iz+0];
s[20] = + g2[ix+0]*g0[iy+0]*g5[iz+0];
s[21] = + g1[ix+0]*g2[iy+0]*g4[iz+0];
s[22] = + g0[ix+0]*g3[iy+0]*g4[iz+0];
s[23] = + g0[ix+0]*g2[iy+0]*g5[iz+0];
s[24] = + g1[ix+0]*g0[iy+0]*g6[iz+0];
s[25] = + g0[ix+0]*g1[iy+0]*g6[iz+0];
s[26] = + g0[ix+0]*g0[iy+0]*g7[iz+0];
if (gout_empty) {
gout[n*27+0] = + s[0];
gout[n*27+1] = + s[1];
gout[n*27+2] = + s[2];
gout[n*27+3] = + s[9];
gout[n*27+4] = + s[10];
gout[n*27+5] = + s[11];
gout[n*27+6] = + s[18];
gout[n*27+7] = + s[19];
gout[n*27+8] = + s[20];
gout[n*27+9] = + s[3];
gout[n*27+10] = + s[4];
gout[n*27+11] = + s[5];
gout[n*27+12] = + s[12];
gout[n*27+13] = + s[13];
gout[n*27+14] = + s[14];
gout[n*27+15] = + s[21];
gout[n*27+16] = + s[22];
gout[n*27+17] = + s[23];
gout[n*27+18] = + s[6];
gout[n*27+19] = + s[7];
gout[n*27+20] = + s[8];
gout[n*27+21] = + s[15];
gout[n*27+22] = + s[16];
gout[n*27+23] = + s[17];
gout[n*27+24] = + s[24];
gout[n*27+25] = + s[25];
gout[n*27+26] = + s[26];
} else {
gout[n*27+0] += + s[0];
gout[n*27+1] += + s[1];
gout[n*27+2] += + s[2];
gout[n*27+3] += + s[9];
gout[n*27+4] += + s[10];
gout[n*27+5] += + s[11];
gout[n*27+6] += + s[18];
gout[n*27+7] += + s[19];
gout[n*27+8] += + s[20];
gout[n*27+9] += + s[3];
gout[n*27+10] += + s[4];
gout[n*27+11] += + s[5];
gout[n*27+12] += + s[12];
gout[n*27+13] += + s[13];
gout[n*27+14] += + s[14];
gout[n*27+15] += + s[21];
gout[n*27+16] += + s[22];
gout[n*27+17] += + s[23];
gout[n*27+18] += + s[6];
gout[n*27+19] += + s[7];
gout[n*27+20] += + s[8];
gout[n*27+21] += + s[15];
gout[n*27+22] += + s[16];
gout[n*27+23] += + s[17];
gout[n*27+24] += + s[24];
gout[n*27+25] += + s[25];
gout[n*27+26] += + s[26];
}}}
void int1e_ipipovlpip_optimizer(CINTOpt **opt, FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env) {
FINT ng[] = {2, 1, 0, 0, 3, 1, 1, 27};
CINTall_1e_optimizer(opt, ng, atm, natm, bas, nbas, env);
}
CACHE_SIZE_T int1e_ipipovlpip_cart(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {2, 1, 0, 0, 3, 1, 1, 27};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipovlpip;
return CINT1e_drv(out, dims, &envs, cache, &c2s_cart_1e, 0);
} // int1e_ipipovlpip_cart
CACHE_SIZE_T int1e_ipipovlpip_sph(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {2, 1, 0, 0, 3, 1, 1, 27};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipovlpip;
return CINT1e_drv(out, dims, &envs, cache, &c2s_sph_1e, 0);
} // int1e_ipipovlpip_sph
CACHE_SIZE_T int1e_ipipovlpip_spinor(double complex *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {2, 1, 0, 0, 3, 1, 1, 27};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipovlpip;
return CINT1e_spinor_drv(out, dims, &envs, cache, &c2s_sf_1e, 0);
} // int1e_ipipovlpip_spinor
ALL_CINT1E(int1e_ipipovlpip)
ALL_CINT1E_FORTRAN_(int1e_ipipovlpip)
/* <NABLA NABLA NABLA NABLA i|OVLP |j> */
void CINTgout1e_int1e_ipipipipovlp(double *gout, double *g, FINT *idx, CINTEnvVars *envs, FINT gout_empty) {
FINT nf = envs->nf;
FINT ix, iy, iz, n;
double *g0 = g;
double *g1 = g0 + envs->g_size * 3;
double *g2 = g1 + envs->g_size * 3;
double *g3 = g2 + envs->g_size * 3;
double *g4 = g3 + envs->g_size * 3;
double *g5 = g4 + envs->g_size * 3;
double *g6 = g5 + envs->g_size * 3;
double *g7 = g6 + envs->g_size * 3;
double *g8 = g7 + envs->g_size * 3;
double *g9 = g8 + envs->g_size * 3;
double *g10 = g9 + envs->g_size * 3;
double *g11 = g10 + envs->g_size * 3;
double *g12 = g11 + envs->g_size * 3;
double *g13 = g12 + envs->g_size * 3;
double *g14 = g13 + envs->g_size * 3;
double *g15 = g14 + envs->g_size * 3;
double s[81];
G1E_D_I(g1, g0, envs->i_l+3, envs->j_l, 0);
G1E_D_I(g2, g0, envs->i_l+2, envs->j_l, 0);
G1E_D_I(g3, g1, envs->i_l+2, envs->j_l, 0);
G1E_D_I(g4, g0, envs->i_l+1, envs->j_l, 0);
G1E_D_I(g5, g1, envs->i_l+1, envs->j_l, 0);
G1E_D_I(g6, g2, envs->i_l+1, envs->j_l, 0);
G1E_D_I(g7, g3, envs->i_l+1, envs->j_l, 0);
G1E_D_I(g8, g0, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g9, g1, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g10, g2, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g11, g3, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g12, g4, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g13, g5, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g14, g6, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g15, g7, envs->i_l+0, envs->j_l, 0);
for (n = 0; n < nf; n++) {
ix = idx[0+n*3];
iy = idx[1+n*3];
iz = idx[2+n*3];
s[0] = + g15[ix+0]*g0[iy+0]*g0[iz+0];
s[1] = + g14[ix+0]*g1[iy+0]*g0[iz+0];
s[2] = + g14[ix+0]*g0[iy+0]*g1[iz+0];
s[3] = + g13[ix+0]*g2[iy+0]*g0[iz+0];
s[4] = + g12[ix+0]*g3[iy+0]*g0[iz+0];
s[5] = + g12[ix+0]*g2[iy+0]*g1[iz+0];
s[6] = + g13[ix+0]*g0[iy+0]*g2[iz+0];
s[7] = + g12[ix+0]*g1[iy+0]*g2[iz+0];
s[8] = + g12[ix+0]*g0[iy+0]*g3[iz+0];
s[9] = + g11[ix+0]*g4[iy+0]*g0[iz+0];
s[10] = + g10[ix+0]*g5[iy+0]*g0[iz+0];
s[11] = + g10[ix+0]*g4[iy+0]*g1[iz+0];
s[12] = + g9[ix+0]*g6[iy+0]*g0[iz+0];
s[13] = + g8[ix+0]*g7[iy+0]*g0[iz+0];
s[14] = + g8[ix+0]*g6[iy+0]*g1[iz+0];
s[15] = + g9[ix+0]*g4[iy+0]*g2[iz+0];
s[16] = + g8[ix+0]*g5[iy+0]*g2[iz+0];
s[17] = + g8[ix+0]*g4[iy+0]*g3[iz+0];
s[18] = + g11[ix+0]*g0[iy+0]*g4[iz+0];
s[19] = + g10[ix+0]*g1[iy+0]*g4[iz+0];
s[20] = + g10[ix+0]*g0[iy+0]*g5[iz+0];
s[21] = + g9[ix+0]*g2[iy+0]*g4[iz+0];
s[22] = + g8[ix+0]*g3[iy+0]*g4[iz+0];
s[23] = + g8[ix+0]*g2[iy+0]*g5[iz+0];
s[24] = + g9[ix+0]*g0[iy+0]*g6[iz+0];
s[25] = + g8[ix+0]*g1[iy+0]*g6[iz+0];
s[26] = + g8[ix+0]*g0[iy+0]*g7[iz+0];
s[27] = + g7[ix+0]*g8[iy+0]*g0[iz+0];
s[28] = + g6[ix+0]*g9[iy+0]*g0[iz+0];
s[29] = + g6[ix+0]*g8[iy+0]*g1[iz+0];
s[30] = + g5[ix+0]*g10[iy+0]*g0[iz+0];
s[31] = + g4[ix+0]*g11[iy+0]*g0[iz+0];
s[32] = + g4[ix+0]*g10[iy+0]*g1[iz+0];
s[33] = + g5[ix+0]*g8[iy+0]*g2[iz+0];
s[34] = + g4[ix+0]*g9[iy+0]*g2[iz+0];
s[35] = + g4[ix+0]*g8[iy+0]*g3[iz+0];
s[36] = + g3[ix+0]*g12[iy+0]*g0[iz+0];
s[37] = + g2[ix+0]*g13[iy+0]*g0[iz+0];
s[38] = + g2[ix+0]*g12[iy+0]*g1[iz+0];
s[39] = + g1[ix+0]*g14[iy+0]*g0[iz+0];
s[40] = + g0[ix+0]*g15[iy+0]*g0[iz+0];
s[41] = + g0[ix+0]*g14[iy+0]*g1[iz+0];
s[42] = + g1[ix+0]*g12[iy+0]*g2[iz+0];
s[43] = + g0[ix+0]*g13[iy+0]*g2[iz+0];
s[44] = + g0[ix+0]*g12[iy+0]*g3[iz+0];
s[45] = + g3[ix+0]*g8[iy+0]*g4[iz+0];
s[46] = + g2[ix+0]*g9[iy+0]*g4[iz+0];
s[47] = + g2[ix+0]*g8[iy+0]*g5[iz+0];
s[48] = + g1[ix+0]*g10[iy+0]*g4[iz+0];
s[49] = + g0[ix+0]*g11[iy+0]*g4[iz+0];
s[50] = + g0[ix+0]*g10[iy+0]*g5[iz+0];
s[51] = + g1[ix+0]*g8[iy+0]*g6[iz+0];
s[52] = + g0[ix+0]*g9[iy+0]*g6[iz+0];
s[53] = + g0[ix+0]*g8[iy+0]*g7[iz+0];
s[54] = + g7[ix+0]*g0[iy+0]*g8[iz+0];
s[55] = + g6[ix+0]*g1[iy+0]*g8[iz+0];
s[56] = + g6[ix+0]*g0[iy+0]*g9[iz+0];
s[57] = + g5[ix+0]*g2[iy+0]*g8[iz+0];
s[58] = + g4[ix+0]*g3[iy+0]*g8[iz+0];
s[59] = + g4[ix+0]*g2[iy+0]*g9[iz+0];
s[60] = + g5[ix+0]*g0[iy+0]*g10[iz+0];
s[61] = + g4[ix+0]*g1[iy+0]*g10[iz+0];
s[62] = + g4[ix+0]*g0[iy+0]*g11[iz+0];
s[63] = + g3[ix+0]*g4[iy+0]*g8[iz+0];
s[64] = + g2[ix+0]*g5[iy+0]*g8[iz+0];
s[65] = + g2[ix+0]*g4[iy+0]*g9[iz+0];
s[66] = + g1[ix+0]*g6[iy+0]*g8[iz+0];
s[67] = + g0[ix+0]*g7[iy+0]*g8[iz+0];
s[68] = + g0[ix+0]*g6[iy+0]*g9[iz+0];
s[69] = + g1[ix+0]*g4[iy+0]*g10[iz+0];
s[70] = + g0[ix+0]*g5[iy+0]*g10[iz+0];
s[71] = + g0[ix+0]*g4[iy+0]*g11[iz+0];
s[72] = + g3[ix+0]*g0[iy+0]*g12[iz+0];
s[73] = + g2[ix+0]*g1[iy+0]*g12[iz+0];
s[74] = + g2[ix+0]*g0[iy+0]*g13[iz+0];
s[75] = + g1[ix+0]*g2[iy+0]*g12[iz+0];
s[76] = + g0[ix+0]*g3[iy+0]*g12[iz+0];
s[77] = + g0[ix+0]*g2[iy+0]*g13[iz+0];
s[78] = + g1[ix+0]*g0[iy+0]*g14[iz+0];
s[79] = + g0[ix+0]*g1[iy+0]*g14[iz+0];
s[80] = + g0[ix+0]*g0[iy+0]*g15[iz+0];
if (gout_empty) {
gout[n*81+0] = + s[0];
gout[n*81+1] = + s[27];
gout[n*81+2] = + s[54];
gout[n*81+3] = + s[9];
gout[n*81+4] = + s[36];
gout[n*81+5] = + s[63];
gout[n*81+6] = + s[18];
gout[n*81+7] = + s[45];
gout[n*81+8] = + s[72];
gout[n*81+9] = + s[3];
gout[n*81+10] = + s[30];
gout[n*81+11] = + s[57];
gout[n*81+12] = + s[12];
gout[n*81+13] = + s[39];
gout[n*81+14] = + s[66];
gout[n*81+15] = + s[21];
gout[n*81+16] = + s[48];
gout[n*81+17] = + s[75];
gout[n*81+18] = + s[6];
gout[n*81+19] = + s[33];
gout[n*81+20] = + s[60];
gout[n*81+21] = + s[15];
gout[n*81+22] = + s[42];
gout[n*81+23] = + s[69];
gout[n*81+24] = + s[24];
gout[n*81+25] = + s[51];
gout[n*81+26] = + s[78];
gout[n*81+27] = + s[1];
gout[n*81+28] = + s[28];
gout[n*81+29] = + s[55];
gout[n*81+30] = + s[10];
gout[n*81+31] = + s[37];
gout[n*81+32] = + s[64];
gout[n*81+33] = + s[19];
gout[n*81+34] = + s[46];
gout[n*81+35] = + s[73];
gout[n*81+36] = + s[4];
gout[n*81+37] = + s[31];
gout[n*81+38] = + s[58];
gout[n*81+39] = + s[13];
gout[n*81+40] = + s[40];
gout[n*81+41] = + s[67];
gout[n*81+42] = + s[22];
gout[n*81+43] = + s[49];
gout[n*81+44] = + s[76];
gout[n*81+45] = + s[7];
gout[n*81+46] = + s[34];
gout[n*81+47] = + s[61];
gout[n*81+48] = + s[16];
gout[n*81+49] = + s[43];
gout[n*81+50] = + s[70];
gout[n*81+51] = + s[25];
gout[n*81+52] = + s[52];
gout[n*81+53] = + s[79];
gout[n*81+54] = + s[2];
gout[n*81+55] = + s[29];
gout[n*81+56] = + s[56];
gout[n*81+57] = + s[11];
gout[n*81+58] = + s[38];
gout[n*81+59] = + s[65];
gout[n*81+60] = + s[20];
gout[n*81+61] = + s[47];
gout[n*81+62] = + s[74];
gout[n*81+63] = + s[5];
gout[n*81+64] = + s[32];
gout[n*81+65] = + s[59];
gout[n*81+66] = + s[14];
gout[n*81+67] = + s[41];
gout[n*81+68] = + s[68];
gout[n*81+69] = + s[23];
gout[n*81+70] = + s[50];
gout[n*81+71] = + s[77];
gout[n*81+72] = + s[8];
gout[n*81+73] = + s[35];
gout[n*81+74] = + s[62];
gout[n*81+75] = + s[17];
gout[n*81+76] = + s[44];
gout[n*81+77] = + s[71];
gout[n*81+78] = + s[26];
gout[n*81+79] = + s[53];
gout[n*81+80] = + s[80];
} else {
gout[n*81+0] += + s[0];
gout[n*81+1] += + s[27];
gout[n*81+2] += + s[54];
gout[n*81+3] += + s[9];
gout[n*81+4] += + s[36];
gout[n*81+5] += + s[63];
gout[n*81+6] += + s[18];
gout[n*81+7] += + s[45];
gout[n*81+8] += + s[72];
gout[n*81+9] += + s[3];
gout[n*81+10] += + s[30];
gout[n*81+11] += + s[57];
gout[n*81+12] += + s[12];
gout[n*81+13] += + s[39];
gout[n*81+14] += + s[66];
gout[n*81+15] += + s[21];
gout[n*81+16] += + s[48];
gout[n*81+17] += + s[75];
gout[n*81+18] += + s[6];
gout[n*81+19] += + s[33];
gout[n*81+20] += + s[60];
gout[n*81+21] += + s[15];
gout[n*81+22] += + s[42];
gout[n*81+23] += + s[69];
gout[n*81+24] += + s[24];
gout[n*81+25] += + s[51];
gout[n*81+26] += + s[78];
gout[n*81+27] += + s[1];
gout[n*81+28] += + s[28];
gout[n*81+29] += + s[55];
gout[n*81+30] += + s[10];
gout[n*81+31] += + s[37];
gout[n*81+32] += + s[64];
gout[n*81+33] += + s[19];
gout[n*81+34] += + s[46];
gout[n*81+35] += + s[73];
gout[n*81+36] += + s[4];
gout[n*81+37] += + s[31];
gout[n*81+38] += + s[58];
gout[n*81+39] += + s[13];
gout[n*81+40] += + s[40];
gout[n*81+41] += + s[67];
gout[n*81+42] += + s[22];
gout[n*81+43] += + s[49];
gout[n*81+44] += + s[76];
gout[n*81+45] += + s[7];
gout[n*81+46] += + s[34];
gout[n*81+47] += + s[61];
gout[n*81+48] += + s[16];
gout[n*81+49] += + s[43];
gout[n*81+50] += + s[70];
gout[n*81+51] += + s[25];
gout[n*81+52] += + s[52];
gout[n*81+53] += + s[79];
gout[n*81+54] += + s[2];
gout[n*81+55] += + s[29];
gout[n*81+56] += + s[56];
gout[n*81+57] += + s[11];
gout[n*81+58] += + s[38];
gout[n*81+59] += + s[65];
gout[n*81+60] += + s[20];
gout[n*81+61] += + s[47];
gout[n*81+62] += + s[74];
gout[n*81+63] += + s[5];
gout[n*81+64] += + s[32];
gout[n*81+65] += + s[59];
gout[n*81+66] += + s[14];
gout[n*81+67] += + s[41];
gout[n*81+68] += + s[68];
gout[n*81+69] += + s[23];
gout[n*81+70] += + s[50];
gout[n*81+71] += + s[77];
gout[n*81+72] += + s[8];
gout[n*81+73] += + s[35];
gout[n*81+74] += + s[62];
gout[n*81+75] += + s[17];
gout[n*81+76] += + s[44];
gout[n*81+77] += + s[71];
gout[n*81+78] += + s[26];
gout[n*81+79] += + s[53];
gout[n*81+80] += + s[80];
}}}
void int1e_ipipipipovlp_optimizer(CINTOpt **opt, FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env) {
FINT ng[] = {4, 0, 0, 0, 4, 1, 1, 81};
CINTall_1e_optimizer(opt, ng, atm, natm, bas, nbas, env);
}
CACHE_SIZE_T int1e_ipipipipovlp_cart(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {4, 0, 0, 0, 4, 1, 1, 81};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipipipovlp;
return CINT1e_drv(out, dims, &envs, cache, &c2s_cart_1e, 0);
} // int1e_ipipipipovlp_cart
CACHE_SIZE_T int1e_ipipipipovlp_sph(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {4, 0, 0, 0, 4, 1, 1, 81};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipipipovlp;
return CINT1e_drv(out, dims, &envs, cache, &c2s_sph_1e, 0);
} // int1e_ipipipipovlp_sph
CACHE_SIZE_T int1e_ipipipipovlp_spinor(double complex *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {4, 0, 0, 0, 4, 1, 1, 81};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipipipovlp;
return CINT1e_spinor_drv(out, dims, &envs, cache, &c2s_sf_1e, 0);
} // int1e_ipipipipovlp_spinor
ALL_CINT1E(int1e_ipipipipovlp)
ALL_CINT1E_FORTRAN_(int1e_ipipipipovlp)
/* <NABLA NABLA NABLA i|OVLP |NABLA j> */
void CINTgout1e_int1e_ipipipovlpip(double *gout, double *g, FINT *idx, CINTEnvVars *envs, FINT gout_empty) {
FINT nf = envs->nf;
FINT ix, iy, iz, n;
double *g0 = g;
double *g1 = g0 + envs->g_size * 3;
double *g2 = g1 + envs->g_size * 3;
double *g3 = g2 + envs->g_size * 3;
double *g4 = g3 + envs->g_size * 3;
double *g5 = g4 + envs->g_size * 3;
double *g6 = g5 + envs->g_size * 3;
double *g7 = g6 + envs->g_size * 3;
double *g8 = g7 + envs->g_size * 3;
double *g9 = g8 + envs->g_size * 3;
double *g10 = g9 + envs->g_size * 3;
double *g11 = g10 + envs->g_size * 3;
double *g12 = g11 + envs->g_size * 3;
double *g13 = g12 + envs->g_size * 3;
double *g14 = g13 + envs->g_size * 3;
double *g15 = g14 + envs->g_size * 3;
double s[81];
G1E_D_J(g1, g0, envs->i_l+3, envs->j_l+0, 0);
G1E_D_I(g2, g0, envs->i_l+2, envs->j_l, 0);
G1E_D_I(g3, g1, envs->i_l+2, envs->j_l, 0);
G1E_D_I(g4, g0, envs->i_l+1, envs->j_l, 0);
G1E_D_I(g5, g1, envs->i_l+1, envs->j_l, 0);
G1E_D_I(g6, g2, envs->i_l+1, envs->j_l, 0);
G1E_D_I(g7, g3, envs->i_l+1, envs->j_l, 0);
G1E_D_I(g8, g0, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g9, g1, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g10, g2, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g11, g3, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g12, g4, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g13, g5, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g14, g6, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g15, g7, envs->i_l+0, envs->j_l, 0);
for (n = 0; n < nf; n++) {
ix = idx[0+n*3];
iy = idx[1+n*3];
iz = idx[2+n*3];
s[0] = + g15[ix+0]*g0[iy+0]*g0[iz+0];
s[1] = + g14[ix+0]*g1[iy+0]*g0[iz+0];
s[2] = + g14[ix+0]*g0[iy+0]*g1[iz+0];
s[3] = + g13[ix+0]*g2[iy+0]*g0[iz+0];
s[4] = + g12[ix+0]*g3[iy+0]*g0[iz+0];
s[5] = + g12[ix+0]*g2[iy+0]*g1[iz+0];
s[6] = + g13[ix+0]*g0[iy+0]*g2[iz+0];
s[7] = + g12[ix+0]*g1[iy+0]*g2[iz+0];
s[8] = + g12[ix+0]*g0[iy+0]*g3[iz+0];
s[9] = + g11[ix+0]*g4[iy+0]*g0[iz+0];
s[10] = + g10[ix+0]*g5[iy+0]*g0[iz+0];
s[11] = + g10[ix+0]*g4[iy+0]*g1[iz+0];
s[12] = + g9[ix+0]*g6[iy+0]*g0[iz+0];
s[13] = + g8[ix+0]*g7[iy+0]*g0[iz+0];
s[14] = + g8[ix+0]*g6[iy+0]*g1[iz+0];
s[15] = + g9[ix+0]*g4[iy+0]*g2[iz+0];
s[16] = + g8[ix+0]*g5[iy+0]*g2[iz+0];
s[17] = + g8[ix+0]*g4[iy+0]*g3[iz+0];
s[18] = + g11[ix+0]*g0[iy+0]*g4[iz+0];
s[19] = + g10[ix+0]*g1[iy+0]*g4[iz+0];
s[20] = + g10[ix+0]*g0[iy+0]*g5[iz+0];
s[21] = + g9[ix+0]*g2[iy+0]*g4[iz+0];
s[22] = + g8[ix+0]*g3[iy+0]*g4[iz+0];
s[23] = + g8[ix+0]*g2[iy+0]*g5[iz+0];
s[24] = + g9[ix+0]*g0[iy+0]*g6[iz+0];
s[25] = + g8[ix+0]*g1[iy+0]*g6[iz+0];
s[26] = + g8[ix+0]*g0[iy+0]*g7[iz+0];
s[27] = + g7[ix+0]*g8[iy+0]*g0[iz+0];
s[28] = + g6[ix+0]*g9[iy+0]*g0[iz+0];
s[29] = + g6[ix+0]*g8[iy+0]*g1[iz+0];
s[30] = + g5[ix+0]*g10[iy+0]*g0[iz+0];
s[31] = + g4[ix+0]*g11[iy+0]*g0[iz+0];
s[32] = + g4[ix+0]*g10[iy+0]*g1[iz+0];
s[33] = + g5[ix+0]*g8[iy+0]*g2[iz+0];
s[34] = + g4[ix+0]*g9[iy+0]*g2[iz+0];
s[35] = + g4[ix+0]*g8[iy+0]*g3[iz+0];
s[36] = + g3[ix+0]*g12[iy+0]*g0[iz+0];
s[37] = + g2[ix+0]*g13[iy+0]*g0[iz+0];
s[38] = + g2[ix+0]*g12[iy+0]*g1[iz+0];
s[39] = + g1[ix+0]*g14[iy+0]*g0[iz+0];
s[40] = + g0[ix+0]*g15[iy+0]*g0[iz+0];
s[41] = + g0[ix+0]*g14[iy+0]*g1[iz+0];
s[42] = + g1[ix+0]*g12[iy+0]*g2[iz+0];
s[43] = + g0[ix+0]*g13[iy+0]*g2[iz+0];
s[44] = + g0[ix+0]*g12[iy+0]*g3[iz+0];
s[45] = + g3[ix+0]*g8[iy+0]*g4[iz+0];
s[46] = + g2[ix+0]*g9[iy+0]*g4[iz+0];
s[47] = + g2[ix+0]*g8[iy+0]*g5[iz+0];
s[48] = + g1[ix+0]*g10[iy+0]*g4[iz+0];
s[49] = + g0[ix+0]*g11[iy+0]*g4[iz+0];
s[50] = + g0[ix+0]*g10[iy+0]*g5[iz+0];
s[51] = + g1[ix+0]*g8[iy+0]*g6[iz+0];
s[52] = + g0[ix+0]*g9[iy+0]*g6[iz+0];
s[53] = + g0[ix+0]*g8[iy+0]*g7[iz+0];
s[54] = + g7[ix+0]*g0[iy+0]*g8[iz+0];
s[55] = + g6[ix+0]*g1[iy+0]*g8[iz+0];
s[56] = + g6[ix+0]*g0[iy+0]*g9[iz+0];
s[57] = + g5[ix+0]*g2[iy+0]*g8[iz+0];
s[58] = + g4[ix+0]*g3[iy+0]*g8[iz+0];
s[59] = + g4[ix+0]*g2[iy+0]*g9[iz+0];
s[60] = + g5[ix+0]*g0[iy+0]*g10[iz+0];
s[61] = + g4[ix+0]*g1[iy+0]*g10[iz+0];
s[62] = + g4[ix+0]*g0[iy+0]*g11[iz+0];
s[63] = + g3[ix+0]*g4[iy+0]*g8[iz+0];
s[64] = + g2[ix+0]*g5[iy+0]*g8[iz+0];
s[65] = + g2[ix+0]*g4[iy+0]*g9[iz+0];
s[66] = + g1[ix+0]*g6[iy+0]*g8[iz+0];
s[67] = + g0[ix+0]*g7[iy+0]*g8[iz+0];
s[68] = + g0[ix+0]*g6[iy+0]*g9[iz+0];
s[69] = + g1[ix+0]*g4[iy+0]*g10[iz+0];
s[70] = + g0[ix+0]*g5[iy+0]*g10[iz+0];
s[71] = + g0[ix+0]*g4[iy+0]*g11[iz+0];
s[72] = + g3[ix+0]*g0[iy+0]*g12[iz+0];
s[73] = + g2[ix+0]*g1[iy+0]*g12[iz+0];
s[74] = + g2[ix+0]*g0[iy+0]*g13[iz+0];
s[75] = + g1[ix+0]*g2[iy+0]*g12[iz+0];
s[76] = + g0[ix+0]*g3[iy+0]*g12[iz+0];
s[77] = + g0[ix+0]*g2[iy+0]*g13[iz+0];
s[78] = + g1[ix+0]*g0[iy+0]*g14[iz+0];
s[79] = + g0[ix+0]*g1[iy+0]*g14[iz+0];
s[80] = + g0[ix+0]*g0[iy+0]*g15[iz+0];
if (gout_empty) {
gout[n*81+0] = + s[0];
gout[n*81+1] = + s[1];
gout[n*81+2] = + s[2];
gout[n*81+3] = + s[27];
gout[n*81+4] = + s[28];
gout[n*81+5] = + s[29];
gout[n*81+6] = + s[54];
gout[n*81+7] = + s[55];
gout[n*81+8] = + s[56];
gout[n*81+9] = + s[9];
gout[n*81+10] = + s[10];
gout[n*81+11] = + s[11];
gout[n*81+12] = + s[36];
gout[n*81+13] = + s[37];
gout[n*81+14] = + s[38];
gout[n*81+15] = + s[63];
gout[n*81+16] = + s[64];
gout[n*81+17] = + s[65];
gout[n*81+18] = + s[18];
gout[n*81+19] = + s[19];
gout[n*81+20] = + s[20];
gout[n*81+21] = + s[45];
gout[n*81+22] = + s[46];
gout[n*81+23] = + s[47];
gout[n*81+24] = + s[72];
gout[n*81+25] = + s[73];
gout[n*81+26] = + s[74];
gout[n*81+27] = + s[3];
gout[n*81+28] = + s[4];
gout[n*81+29] = + s[5];
gout[n*81+30] = + s[30];
gout[n*81+31] = + s[31];
gout[n*81+32] = + s[32];
gout[n*81+33] = + s[57];
gout[n*81+34] = + s[58];
gout[n*81+35] = + s[59];
gout[n*81+36] = + s[12];
gout[n*81+37] = + s[13];
gout[n*81+38] = + s[14];
gout[n*81+39] = + s[39];
gout[n*81+40] = + s[40];
gout[n*81+41] = + s[41];
gout[n*81+42] = + s[66];
gout[n*81+43] = + s[67];
gout[n*81+44] = + s[68];
gout[n*81+45] = + s[21];
gout[n*81+46] = + s[22];
gout[n*81+47] = + s[23];
gout[n*81+48] = + s[48];
gout[n*81+49] = + s[49];
gout[n*81+50] = + s[50];
gout[n*81+51] = + s[75];
gout[n*81+52] = + s[76];
gout[n*81+53] = + s[77];
gout[n*81+54] = + s[6];
gout[n*81+55] = + s[7];
gout[n*81+56] = + s[8];
gout[n*81+57] = + s[33];
gout[n*81+58] = + s[34];
gout[n*81+59] = + s[35];
gout[n*81+60] = + s[60];
gout[n*81+61] = + s[61];
gout[n*81+62] = + s[62];
gout[n*81+63] = + s[15];
gout[n*81+64] = + s[16];
gout[n*81+65] = + s[17];
gout[n*81+66] = + s[42];
gout[n*81+67] = + s[43];
gout[n*81+68] = + s[44];
gout[n*81+69] = + s[69];
gout[n*81+70] = + s[70];
gout[n*81+71] = + s[71];
gout[n*81+72] = + s[24];
gout[n*81+73] = + s[25];
gout[n*81+74] = + s[26];
gout[n*81+75] = + s[51];
gout[n*81+76] = + s[52];
gout[n*81+77] = + s[53];
gout[n*81+78] = + s[78];
gout[n*81+79] = + s[79];
gout[n*81+80] = + s[80];
} else {
gout[n*81+0] += + s[0];
gout[n*81+1] += + s[1];
gout[n*81+2] += + s[2];
gout[n*81+3] += + s[27];
gout[n*81+4] += + s[28];
gout[n*81+5] += + s[29];
gout[n*81+6] += + s[54];
gout[n*81+7] += + s[55];
gout[n*81+8] += + s[56];
gout[n*81+9] += + s[9];
gout[n*81+10] += + s[10];
gout[n*81+11] += + s[11];
gout[n*81+12] += + s[36];
gout[n*81+13] += + s[37];
gout[n*81+14] += + s[38];
gout[n*81+15] += + s[63];
gout[n*81+16] += + s[64];
gout[n*81+17] += + s[65];
gout[n*81+18] += + s[18];
gout[n*81+19] += + s[19];
gout[n*81+20] += + s[20];
gout[n*81+21] += + s[45];
gout[n*81+22] += + s[46];
gout[n*81+23] += + s[47];
gout[n*81+24] += + s[72];
gout[n*81+25] += + s[73];
gout[n*81+26] += + s[74];
gout[n*81+27] += + s[3];
gout[n*81+28] += + s[4];
gout[n*81+29] += + s[5];
gout[n*81+30] += + s[30];
gout[n*81+31] += + s[31];
gout[n*81+32] += + s[32];
gout[n*81+33] += + s[57];
gout[n*81+34] += + s[58];
gout[n*81+35] += + s[59];
gout[n*81+36] += + s[12];
gout[n*81+37] += + s[13];
gout[n*81+38] += + s[14];
gout[n*81+39] += + s[39];
gout[n*81+40] += + s[40];
gout[n*81+41] += + s[41];
gout[n*81+42] += + s[66];
gout[n*81+43] += + s[67];
gout[n*81+44] += + s[68];
gout[n*81+45] += + s[21];
gout[n*81+46] += + s[22];
gout[n*81+47] += + s[23];
gout[n*81+48] += + s[48];
gout[n*81+49] += + s[49];
gout[n*81+50] += + s[50];
gout[n*81+51] += + s[75];
gout[n*81+52] += + s[76];
gout[n*81+53] += + s[77];
gout[n*81+54] += + s[6];
gout[n*81+55] += + s[7];
gout[n*81+56] += + s[8];
gout[n*81+57] += + s[33];
gout[n*81+58] += + s[34];
gout[n*81+59] += + s[35];
gout[n*81+60] += + s[60];
gout[n*81+61] += + s[61];
gout[n*81+62] += + s[62];
gout[n*81+63] += + s[15];
gout[n*81+64] += + s[16];
gout[n*81+65] += + s[17];
gout[n*81+66] += + s[42];
gout[n*81+67] += + s[43];
gout[n*81+68] += + s[44];
gout[n*81+69] += + s[69];
gout[n*81+70] += + s[70];
gout[n*81+71] += + s[71];
gout[n*81+72] += + s[24];
gout[n*81+73] += + s[25];
gout[n*81+74] += + s[26];
gout[n*81+75] += + s[51];
gout[n*81+76] += + s[52];
gout[n*81+77] += + s[53];
gout[n*81+78] += + s[78];
gout[n*81+79] += + s[79];
gout[n*81+80] += + s[80];
}}}
void int1e_ipipipovlpip_optimizer(CINTOpt **opt, FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env) {
FINT ng[] = {3, 1, 0, 0, 4, 1, 1, 81};
CINTall_1e_optimizer(opt, ng, atm, natm, bas, nbas, env);
}
CACHE_SIZE_T int1e_ipipipovlpip_cart(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {3, 1, 0, 0, 4, 1, 1, 81};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipipovlpip;
return CINT1e_drv(out, dims, &envs, cache, &c2s_cart_1e, 0);
} // int1e_ipipipovlpip_cart
CACHE_SIZE_T int1e_ipipipovlpip_sph(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {3, 1, 0, 0, 4, 1, 1, 81};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipipovlpip;
return CINT1e_drv(out, dims, &envs, cache, &c2s_sph_1e, 0);
} // int1e_ipipipovlpip_sph
CACHE_SIZE_T int1e_ipipipovlpip_spinor(double complex *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {3, 1, 0, 0, 4, 1, 1, 81};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipipovlpip;
return CINT1e_spinor_drv(out, dims, &envs, cache, &c2s_sf_1e, 0);
} // int1e_ipipipovlpip_spinor
ALL_CINT1E(int1e_ipipipovlpip)
ALL_CINT1E_FORTRAN_(int1e_ipipipovlpip)
/* <NABLA NABLA i|OVLP |NABLA NABLA j> */
void CINTgout1e_int1e_ipipovlpipip(double *gout, double *g, FINT *idx, CINTEnvVars *envs, FINT gout_empty) {
FINT nf = envs->nf;
FINT ix, iy, iz, n;
double *g0 = g;
double *g1 = g0 + envs->g_size * 3;
double *g2 = g1 + envs->g_size * 3;
double *g3 = g2 + envs->g_size * 3;
double *g4 = g3 + envs->g_size * 3;
double *g5 = g4 + envs->g_size * 3;
double *g6 = g5 + envs->g_size * 3;
double *g7 = g6 + envs->g_size * 3;
double *g8 = g7 + envs->g_size * 3;
double *g9 = g8 + envs->g_size * 3;
double *g10 = g9 + envs->g_size * 3;
double *g11 = g10 + envs->g_size * 3;
double *g12 = g11 + envs->g_size * 3;
double *g13 = g12 + envs->g_size * 3;
double *g14 = g13 + envs->g_size * 3;
double *g15 = g14 + envs->g_size * 3;
double s[81];
G1E_D_J(g1, g0, envs->i_l+2, envs->j_l+0, 0);
G1E_D_J(g2, g0, envs->i_l+2, envs->j_l+1, 0);
G1E_D_J(g3, g2, envs->i_l+2, envs->j_l+0, 0);
G1E_D_I(g4, g0, envs->i_l+1, envs->j_l, 0);
G1E_D_I(g5, g1, envs->i_l+1, envs->j_l, 0);
G1E_D_I(g6, g2, envs->i_l+1, envs->j_l, 0);
G1E_D_I(g7, g3, envs->i_l+1, envs->j_l, 0);
G1E_D_I(g8, g0, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g9, g1, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g10, g2, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g11, g3, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g12, g4, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g13, g5, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g14, g6, envs->i_l+0, envs->j_l, 0);
G1E_D_I(g15, g7, envs->i_l+0, envs->j_l, 0);
for (n = 0; n < nf; n++) {
ix = idx[0+n*3];
iy = idx[1+n*3];
iz = idx[2+n*3];
s[0] = + g15[ix+0]*g0[iy+0]*g0[iz+0];
s[1] = + g14[ix+0]*g1[iy+0]*g0[iz+0];
s[2] = + g14[ix+0]*g0[iy+0]*g1[iz+0];
s[3] = + g13[ix+0]*g2[iy+0]*g0[iz+0];
s[4] = + g12[ix+0]*g3[iy+0]*g0[iz+0];
s[5] = + g12[ix+0]*g2[iy+0]*g1[iz+0];
s[6] = + g13[ix+0]*g0[iy+0]*g2[iz+0];
s[7] = + g12[ix+0]*g1[iy+0]*g2[iz+0];
s[8] = + g12[ix+0]*g0[iy+0]*g3[iz+0];
s[9] = + g11[ix+0]*g4[iy+0]*g0[iz+0];
s[10] = + g10[ix+0]*g5[iy+0]*g0[iz+0];
s[11] = + g10[ix+0]*g4[iy+0]*g1[iz+0];
s[12] = + g9[ix+0]*g6[iy+0]*g0[iz+0];
s[13] = + g8[ix+0]*g7[iy+0]*g0[iz+0];
s[14] = + g8[ix+0]*g6[iy+0]*g1[iz+0];
s[15] = + g9[ix+0]*g4[iy+0]*g2[iz+0];
s[16] = + g8[ix+0]*g5[iy+0]*g2[iz+0];
s[17] = + g8[ix+0]*g4[iy+0]*g3[iz+0];
s[18] = + g11[ix+0]*g0[iy+0]*g4[iz+0];
s[19] = + g10[ix+0]*g1[iy+0]*g4[iz+0];
s[20] = + g10[ix+0]*g0[iy+0]*g5[iz+0];
s[21] = + g9[ix+0]*g2[iy+0]*g4[iz+0];
s[22] = + g8[ix+0]*g3[iy+0]*g4[iz+0];
s[23] = + g8[ix+0]*g2[iy+0]*g5[iz+0];
s[24] = + g9[ix+0]*g0[iy+0]*g6[iz+0];
s[25] = + g8[ix+0]*g1[iy+0]*g6[iz+0];
s[26] = + g8[ix+0]*g0[iy+0]*g7[iz+0];
s[27] = + g7[ix+0]*g8[iy+0]*g0[iz+0];
s[28] = + g6[ix+0]*g9[iy+0]*g0[iz+0];
s[29] = + g6[ix+0]*g8[iy+0]*g1[iz+0];
s[30] = + g5[ix+0]*g10[iy+0]*g0[iz+0];
s[31] = + g4[ix+0]*g11[iy+0]*g0[iz+0];
s[32] = + g4[ix+0]*g10[iy+0]*g1[iz+0];
s[33] = + g5[ix+0]*g8[iy+0]*g2[iz+0];
s[34] = + g4[ix+0]*g9[iy+0]*g2[iz+0];
s[35] = + g4[ix+0]*g8[iy+0]*g3[iz+0];
s[36] = + g3[ix+0]*g12[iy+0]*g0[iz+0];
s[37] = + g2[ix+0]*g13[iy+0]*g0[iz+0];
s[38] = + g2[ix+0]*g12[iy+0]*g1[iz+0];
s[39] = + g1[ix+0]*g14[iy+0]*g0[iz+0];
s[40] = + g0[ix+0]*g15[iy+0]*g0[iz+0];
s[41] = + g0[ix+0]*g14[iy+0]*g1[iz+0];
s[42] = + g1[ix+0]*g12[iy+0]*g2[iz+0];
s[43] = + g0[ix+0]*g13[iy+0]*g2[iz+0];
s[44] = + g0[ix+0]*g12[iy+0]*g3[iz+0];
s[45] = + g3[ix+0]*g8[iy+0]*g4[iz+0];
s[46] = + g2[ix+0]*g9[iy+0]*g4[iz+0];
s[47] = + g2[ix+0]*g8[iy+0]*g5[iz+0];
s[48] = + g1[ix+0]*g10[iy+0]*g4[iz+0];
s[49] = + g0[ix+0]*g11[iy+0]*g4[iz+0];
s[50] = + g0[ix+0]*g10[iy+0]*g5[iz+0];
s[51] = + g1[ix+0]*g8[iy+0]*g6[iz+0];
s[52] = + g0[ix+0]*g9[iy+0]*g6[iz+0];
s[53] = + g0[ix+0]*g8[iy+0]*g7[iz+0];
s[54] = + g7[ix+0]*g0[iy+0]*g8[iz+0];
s[55] = + g6[ix+0]*g1[iy+0]*g8[iz+0];
s[56] = + g6[ix+0]*g0[iy+0]*g9[iz+0];
s[57] = + g5[ix+0]*g2[iy+0]*g8[iz+0];
s[58] = + g4[ix+0]*g3[iy+0]*g8[iz+0];
s[59] = + g4[ix+0]*g2[iy+0]*g9[iz+0];
s[60] = + g5[ix+0]*g0[iy+0]*g10[iz+0];
s[61] = + g4[ix+0]*g1[iy+0]*g10[iz+0];
s[62] = + g4[ix+0]*g0[iy+0]*g11[iz+0];
s[63] = + g3[ix+0]*g4[iy+0]*g8[iz+0];
s[64] = + g2[ix+0]*g5[iy+0]*g8[iz+0];
s[65] = + g2[ix+0]*g4[iy+0]*g9[iz+0];
s[66] = + g1[ix+0]*g6[iy+0]*g8[iz+0];
s[67] = + g0[ix+0]*g7[iy+0]*g8[iz+0];
s[68] = + g0[ix+0]*g6[iy+0]*g9[iz+0];
s[69] = + g1[ix+0]*g4[iy+0]*g10[iz+0];
s[70] = + g0[ix+0]*g5[iy+0]*g10[iz+0];
s[71] = + g0[ix+0]*g4[iy+0]*g11[iz+0];
s[72] = + g3[ix+0]*g0[iy+0]*g12[iz+0];
s[73] = + g2[ix+0]*g1[iy+0]*g12[iz+0];
s[74] = + g2[ix+0]*g0[iy+0]*g13[iz+0];
s[75] = + g1[ix+0]*g2[iy+0]*g12[iz+0];
s[76] = + g0[ix+0]*g3[iy+0]*g12[iz+0];
s[77] = + g0[ix+0]*g2[iy+0]*g13[iz+0];
s[78] = + g1[ix+0]*g0[iy+0]*g14[iz+0];
s[79] = + g0[ix+0]*g1[iy+0]*g14[iz+0];
s[80] = + g0[ix+0]*g0[iy+0]*g15[iz+0];
if (gout_empty) {
gout[n*81+0] = + s[0];
gout[n*81+1] = + s[1];
gout[n*81+2] = + s[2];
gout[n*81+3] = + s[3];
gout[n*81+4] = + s[4];
gout[n*81+5] = + s[5];
gout[n*81+6] = + s[6];
gout[n*81+7] = + s[7];
gout[n*81+8] = + s[8];
gout[n*81+9] = + s[27];
gout[n*81+10] = + s[28];
gout[n*81+11] = + s[29];
gout[n*81+12] = + s[30];
gout[n*81+13] = + s[31];
gout[n*81+14] = + s[32];
gout[n*81+15] = + s[33];
gout[n*81+16] = + s[34];
gout[n*81+17] = + s[35];
gout[n*81+18] = + s[54];
gout[n*81+19] = + s[55];
gout[n*81+20] = + s[56];
gout[n*81+21] = + s[57];
gout[n*81+22] = + s[58];
gout[n*81+23] = + s[59];
gout[n*81+24] = + s[60];
gout[n*81+25] = + s[61];
gout[n*81+26] = + s[62];
gout[n*81+27] = + s[9];
gout[n*81+28] = + s[10];
gout[n*81+29] = + s[11];
gout[n*81+30] = + s[12];
gout[n*81+31] = + s[13];
gout[n*81+32] = + s[14];
gout[n*81+33] = + s[15];
gout[n*81+34] = + s[16];
gout[n*81+35] = + s[17];
gout[n*81+36] = + s[36];
gout[n*81+37] = + s[37];
gout[n*81+38] = + s[38];
gout[n*81+39] = + s[39];
gout[n*81+40] = + s[40];
gout[n*81+41] = + s[41];
gout[n*81+42] = + s[42];
gout[n*81+43] = + s[43];
gout[n*81+44] = + s[44];
gout[n*81+45] = + s[63];
gout[n*81+46] = + s[64];
gout[n*81+47] = + s[65];
gout[n*81+48] = + s[66];
gout[n*81+49] = + s[67];
gout[n*81+50] = + s[68];
gout[n*81+51] = + s[69];
gout[n*81+52] = + s[70];
gout[n*81+53] = + s[71];
gout[n*81+54] = + s[18];
gout[n*81+55] = + s[19];
gout[n*81+56] = + s[20];
gout[n*81+57] = + s[21];
gout[n*81+58] = + s[22];
gout[n*81+59] = + s[23];
gout[n*81+60] = + s[24];
gout[n*81+61] = + s[25];
gout[n*81+62] = + s[26];
gout[n*81+63] = + s[45];
gout[n*81+64] = + s[46];
gout[n*81+65] = + s[47];
gout[n*81+66] = + s[48];
gout[n*81+67] = + s[49];
gout[n*81+68] = + s[50];
gout[n*81+69] = + s[51];
gout[n*81+70] = + s[52];
gout[n*81+71] = + s[53];
gout[n*81+72] = + s[72];
gout[n*81+73] = + s[73];
gout[n*81+74] = + s[74];
gout[n*81+75] = + s[75];
gout[n*81+76] = + s[76];
gout[n*81+77] = + s[77];
gout[n*81+78] = + s[78];
gout[n*81+79] = + s[79];
gout[n*81+80] = + s[80];
} else {
gout[n*81+0] += + s[0];
gout[n*81+1] += + s[1];
gout[n*81+2] += + s[2];
gout[n*81+3] += + s[3];
gout[n*81+4] += + s[4];
gout[n*81+5] += + s[5];
gout[n*81+6] += + s[6];
gout[n*81+7] += + s[7];
gout[n*81+8] += + s[8];
gout[n*81+9] += + s[27];
gout[n*81+10] += + s[28];
gout[n*81+11] += + s[29];
gout[n*81+12] += + s[30];
gout[n*81+13] += + s[31];
gout[n*81+14] += + s[32];
gout[n*81+15] += + s[33];
gout[n*81+16] += + s[34];
gout[n*81+17] += + s[35];
gout[n*81+18] += + s[54];
gout[n*81+19] += + s[55];
gout[n*81+20] += + s[56];
gout[n*81+21] += + s[57];
gout[n*81+22] += + s[58];
gout[n*81+23] += + s[59];
gout[n*81+24] += + s[60];
gout[n*81+25] += + s[61];
gout[n*81+26] += + s[62];
gout[n*81+27] += + s[9];
gout[n*81+28] += + s[10];
gout[n*81+29] += + s[11];
gout[n*81+30] += + s[12];
gout[n*81+31] += + s[13];
gout[n*81+32] += + s[14];
gout[n*81+33] += + s[15];
gout[n*81+34] += + s[16];
gout[n*81+35] += + s[17];
gout[n*81+36] += + s[36];
gout[n*81+37] += + s[37];
gout[n*81+38] += + s[38];
gout[n*81+39] += + s[39];
gout[n*81+40] += + s[40];
gout[n*81+41] += + s[41];
gout[n*81+42] += + s[42];
gout[n*81+43] += + s[43];
gout[n*81+44] += + s[44];
gout[n*81+45] += + s[63];
gout[n*81+46] += + s[64];
gout[n*81+47] += + s[65];
gout[n*81+48] += + s[66];
gout[n*81+49] += + s[67];
gout[n*81+50] += + s[68];
gout[n*81+51] += + s[69];
gout[n*81+52] += + s[70];
gout[n*81+53] += + s[71];
gout[n*81+54] += + s[18];
gout[n*81+55] += + s[19];
gout[n*81+56] += + s[20];
gout[n*81+57] += + s[21];
gout[n*81+58] += + s[22];
gout[n*81+59] += + s[23];
gout[n*81+60] += + s[24];
gout[n*81+61] += + s[25];
gout[n*81+62] += + s[26];
gout[n*81+63] += + s[45];
gout[n*81+64] += + s[46];
gout[n*81+65] += + s[47];
gout[n*81+66] += + s[48];
gout[n*81+67] += + s[49];
gout[n*81+68] += + s[50];
gout[n*81+69] += + s[51];
gout[n*81+70] += + s[52];
gout[n*81+71] += + s[53];
gout[n*81+72] += + s[72];
gout[n*81+73] += + s[73];
gout[n*81+74] += + s[74];
gout[n*81+75] += + s[75];
gout[n*81+76] += + s[76];
gout[n*81+77] += + s[77];
gout[n*81+78] += + s[78];
gout[n*81+79] += + s[79];
gout[n*81+80] += + s[80];
}}}
void int1e_ipipovlpipip_optimizer(CINTOpt **opt, FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env) {
FINT ng[] = {2, 2, 0, 0, 4, 1, 1, 81};
CINTall_1e_optimizer(opt, ng, atm, natm, bas, nbas, env);
}
CACHE_SIZE_T int1e_ipipovlpipip_cart(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {2, 2, 0, 0, 4, 1, 1, 81};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipovlpipip;
return CINT1e_drv(out, dims, &envs, cache, &c2s_cart_1e, 0);
} // int1e_ipipovlpipip_cart
CACHE_SIZE_T int1e_ipipovlpipip_sph(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {2, 2, 0, 0, 4, 1, 1, 81};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipovlpipip;
return CINT1e_drv(out, dims, &envs, cache, &c2s_sph_1e, 0);
} // int1e_ipipovlpipip_sph
CACHE_SIZE_T int1e_ipipovlpipip_spinor(double complex *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {2, 2, 0, 0, 4, 1, 1, 81};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_ipipovlpipip;
return CINT1e_spinor_drv(out, dims, &envs, cache, &c2s_sf_1e, 0);
} // int1e_ipipovlpipip_spinor
ALL_CINT1E(int1e_ipipovlpipip)
ALL_CINT1E_FORTRAN_(int1e_ipipovlpipip)
/* <RI DOT RI i|OVLP |j> */
void CINTgout1e_int1e_rrovlp(double *gout, double *g, FINT *idx, CINTEnvVars *envs, FINT gout_empty) {
FINT nf = envs->nf;
FINT ix, iy, iz, n;
double *g0 = g;
double *g1 = g0 + envs->g_size * 3;
double *g2 = g1 + envs->g_size * 3;
double *g3 = g2 + envs->g_size * 3;
double dri[3];
dri[0] = envs->ri[0] - envs->ri[0];
dri[1] = envs->ri[1] - envs->ri[1];
dri[2] = envs->ri[2] - envs->ri[2];
double s[9];
G1E_RCI(g1, g0, envs->i_l+1, envs->j_l, 0);
G1E_RCI(g2, g0, envs->i_l+0, envs->j_l, 0);
G1E_RCI(g3, g1, envs->i_l+0, envs->j_l, 0);
for (n = 0; n < nf; n++) {
ix = idx[0+n*3];
iy = idx[1+n*3];
iz = idx[2+n*3];
s[0] = + g3[ix+0]*g0[iy+0]*g0[iz+0];
s[1] = + g2[ix+0]*g1[iy+0]*g0[iz+0];
s[2] = + g2[ix+0]*g0[iy+0]*g1[iz+0];
s[3] = + g1[ix+0]*g2[iy+0]*g0[iz+0];
s[4] = + g0[ix+0]*g3[iy+0]*g0[iz+0];
s[5] = + g0[ix+0]*g2[iy+0]*g1[iz+0];
s[6] = + g1[ix+0]*g0[iy+0]*g2[iz+0];
s[7] = + g0[ix+0]*g1[iy+0]*g2[iz+0];
s[8] = + g0[ix+0]*g0[iy+0]*g3[iz+0];
if (gout_empty) {
gout[n*1+0] = + s[0] + s[4] + s[8];
} else {
gout[n*1+0] += + s[0] + s[4] + s[8];
}}}
void int1e_rrovlp_optimizer(CINTOpt **opt, FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env) {
FINT ng[] = {2, 0, 0, 0, 2, 1, 1, 1};
CINTall_1e_optimizer(opt, ng, atm, natm, bas, nbas, env);
}
CACHE_SIZE_T int1e_rrovlp_cart(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {2, 0, 0, 0, 2, 1, 1, 1};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_rrovlp;
return CINT1e_drv(out, dims, &envs, cache, &c2s_cart_1e, 0);
} // int1e_rrovlp_cart
CACHE_SIZE_T int1e_rrovlp_sph(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {2, 0, 0, 0, 2, 1, 1, 1};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_rrovlp;
return CINT1e_drv(out, dims, &envs, cache, &c2s_sph_1e, 0);
} // int1e_rrovlp_sph
CACHE_SIZE_T int1e_rrovlp_spinor(double complex *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {2, 0, 0, 0, 2, 1, 1, 1};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_rrovlp;
return CINT1e_spinor_drv(out, dims, &envs, cache, &c2s_sf_1e, 0);
} // int1e_rrovlp_spinor
ALL_CINT1E(int1e_rrovlp)
ALL_CINT1E_FORTRAN_(int1e_rrovlp)
/* <RI DOT RI RI DOT RI i|OVLP |j> */
void CINTgout1e_int1e_rrrrovlp(double *gout, double *g, FINT *idx, CINTEnvVars *envs, FINT gout_empty) {
FINT nf = envs->nf;
FINT ix, iy, iz, n;
double *g0 = g;
double *g1 = g0 + envs->g_size * 3;
double *g2 = g1 + envs->g_size * 3;
double *g3 = g2 + envs->g_size * 3;
double *g4 = g3 + envs->g_size * 3;
double *g5 = g4 + envs->g_size * 3;
double *g6 = g5 + envs->g_size * 3;
double *g7 = g6 + envs->g_size * 3;
double *g8 = g7 + envs->g_size * 3;
double *g9 = g8 + envs->g_size * 3;
double *g10 = g9 + envs->g_size * 3;
double *g11 = g10 + envs->g_size * 3;
double *g12 = g11 + envs->g_size * 3;
double *g13 = g12 + envs->g_size * 3;
double *g14 = g13 + envs->g_size * 3;
double *g15 = g14 + envs->g_size * 3;
double dri[3];
dri[0] = envs->ri[0] - envs->ri[0];
dri[1] = envs->ri[1] - envs->ri[1];
dri[2] = envs->ri[2] - envs->ri[2];
double s[81];
G1E_RCI(g1, g0, envs->i_l+3, envs->j_l, 0);
G1E_RCI(g2, g0, envs->i_l+2, envs->j_l, 0);
G1E_RCI(g3, g1, envs->i_l+2, envs->j_l, 0);
G1E_RCI(g4, g0, envs->i_l+1, envs->j_l, 0);
G1E_RCI(g5, g1, envs->i_l+1, envs->j_l, 0);
G1E_RCI(g6, g2, envs->i_l+1, envs->j_l, 0);
G1E_RCI(g7, g3, envs->i_l+1, envs->j_l, 0);
G1E_RCI(g8, g0, envs->i_l+0, envs->j_l, 0);
G1E_RCI(g9, g1, envs->i_l+0, envs->j_l, 0);
G1E_RCI(g10, g2, envs->i_l+0, envs->j_l, 0);
G1E_RCI(g11, g3, envs->i_l+0, envs->j_l, 0);
G1E_RCI(g12, g4, envs->i_l+0, envs->j_l, 0);
G1E_RCI(g13, g5, envs->i_l+0, envs->j_l, 0);
G1E_RCI(g14, g6, envs->i_l+0, envs->j_l, 0);
G1E_RCI(g15, g7, envs->i_l+0, envs->j_l, 0);
for (n = 0; n < nf; n++) {
ix = idx[0+n*3];
iy = idx[1+n*3];
iz = idx[2+n*3];
s[0] = + g15[ix+0]*g0[iy+0]*g0[iz+0];
s[1] = + g14[ix+0]*g1[iy+0]*g0[iz+0];
s[2] = + g14[ix+0]*g0[iy+0]*g1[iz+0];
s[3] = + g13[ix+0]*g2[iy+0]*g0[iz+0];
s[4] = + g12[ix+0]*g3[iy+0]*g0[iz+0];
s[5] = + g12[ix+0]*g2[iy+0]*g1[iz+0];
s[6] = + g13[ix+0]*g0[iy+0]*g2[iz+0];
s[7] = + g12[ix+0]*g1[iy+0]*g2[iz+0];
s[8] = + g12[ix+0]*g0[iy+0]*g3[iz+0];
s[9] = + g11[ix+0]*g4[iy+0]*g0[iz+0];
s[10] = + g10[ix+0]*g5[iy+0]*g0[iz+0];
s[11] = + g10[ix+0]*g4[iy+0]*g1[iz+0];
s[12] = + g9[ix+0]*g6[iy+0]*g0[iz+0];
s[13] = + g8[ix+0]*g7[iy+0]*g0[iz+0];
s[14] = + g8[ix+0]*g6[iy+0]*g1[iz+0];
s[15] = + g9[ix+0]*g4[iy+0]*g2[iz+0];
s[16] = + g8[ix+0]*g5[iy+0]*g2[iz+0];
s[17] = + g8[ix+0]*g4[iy+0]*g3[iz+0];
s[18] = + g11[ix+0]*g0[iy+0]*g4[iz+0];
s[19] = + g10[ix+0]*g1[iy+0]*g4[iz+0];
s[20] = + g10[ix+0]*g0[iy+0]*g5[iz+0];
s[21] = + g9[ix+0]*g2[iy+0]*g4[iz+0];
s[22] = + g8[ix+0]*g3[iy+0]*g4[iz+0];
s[23] = + g8[ix+0]*g2[iy+0]*g5[iz+0];
s[24] = + g9[ix+0]*g0[iy+0]*g6[iz+0];
s[25] = + g8[ix+0]*g1[iy+0]*g6[iz+0];
s[26] = + g8[ix+0]*g0[iy+0]*g7[iz+0];
s[27] = + g7[ix+0]*g8[iy+0]*g0[iz+0];
s[28] = + g6[ix+0]*g9[iy+0]*g0[iz+0];
s[29] = + g6[ix+0]*g8[iy+0]*g1[iz+0];
s[30] = + g5[ix+0]*g10[iy+0]*g0[iz+0];
s[31] = + g4[ix+0]*g11[iy+0]*g0[iz+0];
s[32] = + g4[ix+0]*g10[iy+0]*g1[iz+0];
s[33] = + g5[ix+0]*g8[iy+0]*g2[iz+0];
s[34] = + g4[ix+0]*g9[iy+0]*g2[iz+0];
s[35] = + g4[ix+0]*g8[iy+0]*g3[iz+0];
s[36] = + g3[ix+0]*g12[iy+0]*g0[iz+0];
s[37] = + g2[ix+0]*g13[iy+0]*g0[iz+0];
s[38] = + g2[ix+0]*g12[iy+0]*g1[iz+0];
s[39] = + g1[ix+0]*g14[iy+0]*g0[iz+0];
s[40] = + g0[ix+0]*g15[iy+0]*g0[iz+0];
s[41] = + g0[ix+0]*g14[iy+0]*g1[iz+0];
s[42] = + g1[ix+0]*g12[iy+0]*g2[iz+0];
s[43] = + g0[ix+0]*g13[iy+0]*g2[iz+0];
s[44] = + g0[ix+0]*g12[iy+0]*g3[iz+0];
s[45] = + g3[ix+0]*g8[iy+0]*g4[iz+0];
s[46] = + g2[ix+0]*g9[iy+0]*g4[iz+0];
s[47] = + g2[ix+0]*g8[iy+0]*g5[iz+0];
s[48] = + g1[ix+0]*g10[iy+0]*g4[iz+0];
s[49] = + g0[ix+0]*g11[iy+0]*g4[iz+0];
s[50] = + g0[ix+0]*g10[iy+0]*g5[iz+0];
s[51] = + g1[ix+0]*g8[iy+0]*g6[iz+0];
s[52] = + g0[ix+0]*g9[iy+0]*g6[iz+0];
s[53] = + g0[ix+0]*g8[iy+0]*g7[iz+0];
s[54] = + g7[ix+0]*g0[iy+0]*g8[iz+0];
s[55] = + g6[ix+0]*g1[iy+0]*g8[iz+0];
s[56] = + g6[ix+0]*g0[iy+0]*g9[iz+0];
s[57] = + g5[ix+0]*g2[iy+0]*g8[iz+0];
s[58] = + g4[ix+0]*g3[iy+0]*g8[iz+0];
s[59] = + g4[ix+0]*g2[iy+0]*g9[iz+0];
s[60] = + g5[ix+0]*g0[iy+0]*g10[iz+0];
s[61] = + g4[ix+0]*g1[iy+0]*g10[iz+0];
s[62] = + g4[ix+0]*g0[iy+0]*g11[iz+0];
s[63] = + g3[ix+0]*g4[iy+0]*g8[iz+0];
s[64] = + g2[ix+0]*g5[iy+0]*g8[iz+0];
s[65] = + g2[ix+0]*g4[iy+0]*g9[iz+0];
s[66] = + g1[ix+0]*g6[iy+0]*g8[iz+0];
s[67] = + g0[ix+0]*g7[iy+0]*g8[iz+0];
s[68] = + g0[ix+0]*g6[iy+0]*g9[iz+0];
s[69] = + g1[ix+0]*g4[iy+0]*g10[iz+0];
s[70] = + g0[ix+0]*g5[iy+0]*g10[iz+0];
s[71] = + g0[ix+0]*g4[iy+0]*g11[iz+0];
s[72] = + g3[ix+0]*g0[iy+0]*g12[iz+0];
s[73] = + g2[ix+0]*g1[iy+0]*g12[iz+0];
s[74] = + g2[ix+0]*g0[iy+0]*g13[iz+0];
s[75] = + g1[ix+0]*g2[iy+0]*g12[iz+0];
s[76] = + g0[ix+0]*g3[iy+0]*g12[iz+0];
s[77] = + g0[ix+0]*g2[iy+0]*g13[iz+0];
s[78] = + g1[ix+0]*g0[iy+0]*g14[iz+0];
s[79] = + g0[ix+0]*g1[iy+0]*g14[iz+0];
s[80] = + g0[ix+0]*g0[iy+0]*g15[iz+0];
if (gout_empty) {
gout[n*1+0] = + s[0] + 2*s[4] + 2*s[8] + s[40] + 2*s[44] + s[80];
} else {
gout[n*1+0] += + s[0] + 2*s[4] + 2*s[8] + s[40] + 2*s[44] + s[80];
}}}
void int1e_rrrrovlp_optimizer(CINTOpt **opt, FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env) {
FINT ng[] = {4, 0, 0, 0, 4, 1, 1, 1};
CINTall_1e_optimizer(opt, ng, atm, natm, bas, nbas, env);
}
CACHE_SIZE_T int1e_rrrrovlp_cart(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {4, 0, 0, 0, 4, 1, 1, 1};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_rrrrovlp;
return CINT1e_drv(out, dims, &envs, cache, &c2s_cart_1e, 0);
} // int1e_rrrrovlp_cart
CACHE_SIZE_T int1e_rrrrovlp_sph(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {4, 0, 0, 0, 4, 1, 1, 1};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_rrrrovlp;
return CINT1e_drv(out, dims, &envs, cache, &c2s_sph_1e, 0);
} // int1e_rrrrovlp_sph
CACHE_SIZE_T int1e_rrrrovlp_spinor(double complex *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {4, 0, 0, 0, 4, 1, 1, 1};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_rrrrovlp;
return CINT1e_spinor_drv(out, dims, &envs, cache, &c2s_sf_1e, 0);
} // int1e_rrrrovlp_spinor
ALL_CINT1E(int1e_rrrrovlp)
ALL_CINT1E_FORTRAN_(int1e_rrrrovlp)
/* <RI DOT RI i|OVLP |RJ DOT RJ j> */
void CINTgout1e_int1e_rrovlprr(double *gout, double *g, FINT *idx, CINTEnvVars *envs, FINT gout_empty) {
FINT nf = envs->nf;
FINT ix, iy, iz, n;
double *g0 = g;
double *g1 = g0 + envs->g_size * 3;
double *g2 = g1 + envs->g_size * 3;
double *g3 = g2 + envs->g_size * 3;
double *g4 = g3 + envs->g_size * 3;
double *g5 = g4 + envs->g_size * 3;
double *g6 = g5 + envs->g_size * 3;
double *g7 = g6 + envs->g_size * 3;
double *g8 = g7 + envs->g_size * 3;
double *g9 = g8 + envs->g_size * 3;
double *g10 = g9 + envs->g_size * 3;
double *g11 = g10 + envs->g_size * 3;
double *g12 = g11 + envs->g_size * 3;
double *g13 = g12 + envs->g_size * 3;
double *g14 = g13 + envs->g_size * 3;
double *g15 = g14 + envs->g_size * 3;
double dri[3];
dri[0] = envs->ri[0] - envs->ri[0];
dri[1] = envs->ri[1] - envs->ri[1];
dri[2] = envs->ri[2] - envs->ri[2];
double drj[3];
drj[0] = envs->rj[0] - envs->rj[0];
drj[1] = envs->rj[1] - envs->rj[1];
drj[2] = envs->rj[2] - envs->rj[2];
double s[81];
G1E_RCJ(g1, g0, envs->i_l+2, envs->j_l+0, 0);
G1E_RCJ(g2, g0, envs->i_l+2, envs->j_l+1, 0);
G1E_RCJ(g3, g2, envs->i_l+2, envs->j_l+0, 0);
G1E_RCI(g4, g0, envs->i_l+1, envs->j_l, 0);
G1E_RCI(g5, g1, envs->i_l+1, envs->j_l, 0);
G1E_RCI(g6, g2, envs->i_l+1, envs->j_l, 0);
G1E_RCI(g7, g3, envs->i_l+1, envs->j_l, 0);
G1E_RCI(g8, g0, envs->i_l+0, envs->j_l, 0);
G1E_RCI(g9, g1, envs->i_l+0, envs->j_l, 0);
G1E_RCI(g10, g2, envs->i_l+0, envs->j_l, 0);
G1E_RCI(g11, g3, envs->i_l+0, envs->j_l, 0);
G1E_RCI(g12, g4, envs->i_l+0, envs->j_l, 0);
G1E_RCI(g13, g5, envs->i_l+0, envs->j_l, 0);
G1E_RCI(g14, g6, envs->i_l+0, envs->j_l, 0);
G1E_RCI(g15, g7, envs->i_l+0, envs->j_l, 0);
for (n = 0; n < nf; n++) {
ix = idx[0+n*3];
iy = idx[1+n*3];
iz = idx[2+n*3];
s[0] = + g15[ix+0]*g0[iy+0]*g0[iz+0];
s[1] = + g14[ix+0]*g1[iy+0]*g0[iz+0];
s[2] = + g14[ix+0]*g0[iy+0]*g1[iz+0];
s[3] = + g13[ix+0]*g2[iy+0]*g0[iz+0];
s[4] = + g12[ix+0]*g3[iy+0]*g0[iz+0];
s[5] = + g12[ix+0]*g2[iy+0]*g1[iz+0];
s[6] = + g13[ix+0]*g0[iy+0]*g2[iz+0];
s[7] = + g12[ix+0]*g1[iy+0]*g2[iz+0];
s[8] = + g12[ix+0]*g0[iy+0]*g3[iz+0];
s[9] = + g11[ix+0]*g4[iy+0]*g0[iz+0];
s[10] = + g10[ix+0]*g5[iy+0]*g0[iz+0];
s[11] = + g10[ix+0]*g4[iy+0]*g1[iz+0];
s[12] = + g9[ix+0]*g6[iy+0]*g0[iz+0];
s[13] = + g8[ix+0]*g7[iy+0]*g0[iz+0];
s[14] = + g8[ix+0]*g6[iy+0]*g1[iz+0];
s[15] = + g9[ix+0]*g4[iy+0]*g2[iz+0];
s[16] = + g8[ix+0]*g5[iy+0]*g2[iz+0];
s[17] = + g8[ix+0]*g4[iy+0]*g3[iz+0];
s[18] = + g11[ix+0]*g0[iy+0]*g4[iz+0];
s[19] = + g10[ix+0]*g1[iy+0]*g4[iz+0];
s[20] = + g10[ix+0]*g0[iy+0]*g5[iz+0];
s[21] = + g9[ix+0]*g2[iy+0]*g4[iz+0];
s[22] = + g8[ix+0]*g3[iy+0]*g4[iz+0];
s[23] = + g8[ix+0]*g2[iy+0]*g5[iz+0];
s[24] = + g9[ix+0]*g0[iy+0]*g6[iz+0];
s[25] = + g8[ix+0]*g1[iy+0]*g6[iz+0];
s[26] = + g8[ix+0]*g0[iy+0]*g7[iz+0];
s[27] = + g7[ix+0]*g8[iy+0]*g0[iz+0];
s[28] = + g6[ix+0]*g9[iy+0]*g0[iz+0];
s[29] = + g6[ix+0]*g8[iy+0]*g1[iz+0];
s[30] = + g5[ix+0]*g10[iy+0]*g0[iz+0];
s[31] = + g4[ix+0]*g11[iy+0]*g0[iz+0];
s[32] = + g4[ix+0]*g10[iy+0]*g1[iz+0];
s[33] = + g5[ix+0]*g8[iy+0]*g2[iz+0];
s[34] = + g4[ix+0]*g9[iy+0]*g2[iz+0];
s[35] = + g4[ix+0]*g8[iy+0]*g3[iz+0];
s[36] = + g3[ix+0]*g12[iy+0]*g0[iz+0];
s[37] = + g2[ix+0]*g13[iy+0]*g0[iz+0];
s[38] = + g2[ix+0]*g12[iy+0]*g1[iz+0];
s[39] = + g1[ix+0]*g14[iy+0]*g0[iz+0];
s[40] = + g0[ix+0]*g15[iy+0]*g0[iz+0];
s[41] = + g0[ix+0]*g14[iy+0]*g1[iz+0];
s[42] = + g1[ix+0]*g12[iy+0]*g2[iz+0];
s[43] = + g0[ix+0]*g13[iy+0]*g2[iz+0];
s[44] = + g0[ix+0]*g12[iy+0]*g3[iz+0];
s[45] = + g3[ix+0]*g8[iy+0]*g4[iz+0];
s[46] = + g2[ix+0]*g9[iy+0]*g4[iz+0];
s[47] = + g2[ix+0]*g8[iy+0]*g5[iz+0];
s[48] = + g1[ix+0]*g10[iy+0]*g4[iz+0];
s[49] = + g0[ix+0]*g11[iy+0]*g4[iz+0];
s[50] = + g0[ix+0]*g10[iy+0]*g5[iz+0];
s[51] = + g1[ix+0]*g8[iy+0]*g6[iz+0];
s[52] = + g0[ix+0]*g9[iy+0]*g6[iz+0];
s[53] = + g0[ix+0]*g8[iy+0]*g7[iz+0];
s[54] = + g7[ix+0]*g0[iy+0]*g8[iz+0];
s[55] = + g6[ix+0]*g1[iy+0]*g8[iz+0];
s[56] = + g6[ix+0]*g0[iy+0]*g9[iz+0];
s[57] = + g5[ix+0]*g2[iy+0]*g8[iz+0];
s[58] = + g4[ix+0]*g3[iy+0]*g8[iz+0];
s[59] = + g4[ix+0]*g2[iy+0]*g9[iz+0];
s[60] = + g5[ix+0]*g0[iy+0]*g10[iz+0];
s[61] = + g4[ix+0]*g1[iy+0]*g10[iz+0];
s[62] = + g4[ix+0]*g0[iy+0]*g11[iz+0];
s[63] = + g3[ix+0]*g4[iy+0]*g8[iz+0];
s[64] = + g2[ix+0]*g5[iy+0]*g8[iz+0];
s[65] = + g2[ix+0]*g4[iy+0]*g9[iz+0];
s[66] = + g1[ix+0]*g6[iy+0]*g8[iz+0];
s[67] = + g0[ix+0]*g7[iy+0]*g8[iz+0];
s[68] = + g0[ix+0]*g6[iy+0]*g9[iz+0];
s[69] = + g1[ix+0]*g4[iy+0]*g10[iz+0];
s[70] = + g0[ix+0]*g5[iy+0]*g10[iz+0];
s[71] = + g0[ix+0]*g4[iy+0]*g11[iz+0];
s[72] = + g3[ix+0]*g0[iy+0]*g12[iz+0];
s[73] = + g2[ix+0]*g1[iy+0]*g12[iz+0];
s[74] = + g2[ix+0]*g0[iy+0]*g13[iz+0];
s[75] = + g1[ix+0]*g2[iy+0]*g12[iz+0];
s[76] = + g0[ix+0]*g3[iy+0]*g12[iz+0];
s[77] = + g0[ix+0]*g2[iy+0]*g13[iz+0];
s[78] = + g1[ix+0]*g0[iy+0]*g14[iz+0];
s[79] = + g0[ix+0]*g1[iy+0]*g14[iz+0];
s[80] = + g0[ix+0]*g0[iy+0]*g15[iz+0];
if (gout_empty) {
gout[n*1+0] = + s[0] + s[36] + s[72] + s[4] + s[40] + s[76] + s[8] + s[44] + s[80];
} else {
gout[n*1+0] += + s[0] + s[36] + s[72] + s[4] + s[40] + s[76] + s[8] + s[44] + s[80];
}}}
void int1e_rrovlprr_optimizer(CINTOpt **opt, FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env) {
FINT ng[] = {2, 2, 0, 0, 4, 1, 1, 1};
CINTall_1e_optimizer(opt, ng, atm, natm, bas, nbas, env);
}
CACHE_SIZE_T int1e_rrovlprr_cart(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {2, 2, 0, 0, 4, 1, 1, 1};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_rrovlprr;
return CINT1e_drv(out, dims, &envs, cache, &c2s_cart_1e, 0);
} // int1e_rrovlprr_cart
CACHE_SIZE_T int1e_rrovlprr_sph(double *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {2, 2, 0, 0, 4, 1, 1, 1};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_rrovlprr;
return CINT1e_drv(out, dims, &envs, cache, &c2s_sph_1e, 0);
} // int1e_rrovlprr_sph
CACHE_SIZE_T int1e_rrovlprr_spinor(double complex *out, FINT *dims, FINT *shls,
FINT *atm, FINT natm, FINT *bas, FINT nbas, double *env, CINTOpt *opt, double *cache) {
FINT ng[] = {2, 2, 0, 0, 4, 1, 1, 1};
CINTEnvVars envs;
CINTinit_int1e_EnvVars(&envs, ng, shls, atm, natm, bas, nbas, env);
envs.f_gout = &CINTgout1e_int1e_rrovlprr;
return CINT1e_spinor_drv(out, dims, &envs, cache, &c2s_sf_1e, 0);
} // int1e_rrovlprr_spinor
ALL_CINT1E(int1e_rrovlprr)
ALL_CINT1E_FORTRAN_(int1e_rrovlprr)
